### ISSUE TITLE
How to style gift_card / password theme using `yarn start`

### ISSUE THREAD

**Issue by dan-gamble** [Shopify/starter-theme#101]
I'm having a bit of an issue with getting no CSS on a local theme file that isn't the `theme.liquid`.

In the `password.liquid` file i've added the below under `{% include 'social-meta-tags' %}`

```jinja
{% include 'style-tags', layout: 'password' %}
{% include 'css-variables' %}
```

And also added a `password.js` to `scripts/layout` with the contents of:

```javascript
import '../../styles/password.scss'
import '../../styles/password.scss.liquid'
```

When i run `yarn deploy` this seems to work fine but when i'm viewing them with my development theme and `yarn start` running i get no CSS. Any other page that uses the `theme.liquid` layout works fine. Is there something i'm missing?

**Comment by dan-gamble** [comment]
🤦‍♂️

Was missing `{% include 'script-tags', layout: 'password' %}`

It could be worth adding this to the base starter theme, happy to PR it in if wanted?

**Comment by t-kelly** [comment]
I'm hesitant about adding `{% include %}` tags where they're not needed. We don't need `script-tags` in `layout/password.liquid` since we're not shipping any JS out of the box with it. It could use the `style-tags` and `css-variables` tag though.

The `layout/gift-card.liquid` could use `script-tags` since we do have some JS for that. Same with the style tags.

PRs are always welcome!

**Comment by dan-gamble** [comment]
Isn't the `script-tags` loading in the CSS via webpack so it's needed for that? I vaguely remember that being the issue here. Could be just a local development thing where it's needed and the CSS works on live projects.

**Comment by t-kelly** [comment]
Oh this is true for development -- didn't think of that. Good call 👍
