### ISSUE TITLE
Any documentation on how to tap into the function that updates variants on option selection?

### ISSUE THREAD

**Issue by adrianocr** [Shopify/starter-theme#115]
The new slate and starter-theme combo seems to load variants handling from `import Variants from '@shopify/theme-variants';` 

But I need to tap into the function that handles updating variants when an option is selected in the options dropdown. 

Any info on how I can go about that?

**Comment by huguestennier** [comment]
`@shopify/theme-variants` lives [here](https://github.com/Shopify/theme-scripts/blob/master/packages/theme-variants/variants.js). Unfortunately, there's no documentation yet but the code should be pretty self explanatory.

Going to close this since it's not Starter Theme specific. Do you mind continuing the discussion in the theme-scripts repo and [on this issue?](https://github.com/Shopify/theme-scripts/issues/44)
